project_id = "mjqlglcrxgwxwhksxvfc"

[functions.send-otp-email]
verify_jwt = true

[functions.verify-otp]
verify_jwt = true

[functions.create-paypal-order]
verify_jwt = true

[functions.capture-paypal-order]
verify_jwt = true

[functions.authorize-paypal-order]
verify_jwt = true

[functions.manage-authorized-paypal-order]
verify_jwt = true

[functions.refund-paypal-order]
verify_jwt = true

[functions.paypal-webhook]
verify_jwt = false

[functions.invite-user]
verify_jwt = true

[functions.sync-offline-orders]
verify_jwt = true


[functions.zettle-paypal-webhook]
verify_jwt = false

[functions.create-cred]
verify_jwt = true

[functions.reconcile-offline-orders]
verify_jwt = true