create extension if not exists "moddatetime" with schema "public" version '1.0';

create table "public"."cred" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "key" text not null,
    "value" text not null,
    "source" text not null,
    "is_active" boolean not null,
    "meta" jsonb not null
);


alter table "public"."cred" enable row level security;

create table "public"."payment_sync" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "provider" text not null,
    "account_id" text default 'default'::text,
    "last_synced_at" timestamp with time zone,
    "metadata" jsonb default '{}'::jsonb,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);


alter table "public"."booking_dates" add column "checked_in_at" timestamp with time zone;

alter table "public"."booking_dates" add column "checked_in_by" uuid;

alter table "public"."bookings" add column "offline_invoice_id" uuid;

alter table "public"."bookings" add column "offline_synced_at" timestamp with time zone;


CREATE UNIQUE INDEX cred_pkey ON public.cred USING btree (id);


CREATE UNIQUE INDEX payment_sync_provider_account_id_key ON public.payment_sync USING btree (provider, account_id);

alter table "public"."cred" add constraint "cred_pkey" PRIMARY KEY using index "cred_pkey";

alter table "public"."booking_dates" add constraint "booking_dates_checked_in_by_fkey" FOREIGN KEY (checked_in_by) REFERENCES profiles(id) not valid;

alter table "public"."booking_dates" validate constraint "booking_dates_checked_in_by_fkey";

alter table "public"."payment_sync" add constraint "payment_sync_provider_account_id_key" UNIQUE using index "payment_sync_provider_account_id_key";

set check_function_bodies = off;

INSERT INTO public.permissions (key, name, description, category) VALUES
  -- Bookings
  ('bookings.undo.checkin', 'Undo Booking Checkin', 'Undo bookings checkin', 'bookings');

INSERT INTO public.role_permissions (role_id, permission_id)
SELECT 
  r.id as role_id,
  p.id as permission_id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE 
  (r.key = 'admin' AND p.key = 'bookings.undo.checkin');

CREATE OR REPLACE FUNCTION public.checkin_vendor(p_booking_id uuid, p_booking_date_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$DECLARE
    v_staff_id uuid;
    v_exists boolean;
    v_status text;
    v_payment_status text;
    v_checked_at timestamptz;
BEGIN
    --------------------------------------------------------------------
    -- Authenticated staff ID
    --------------------------------------------------------------------
    v_staff_id := auth.uid();
    IF v_staff_id IS NULL THEN
        RAISE EXCEPTION 'Unauthenticated user'
        USING errcode = 'P4000';
    END IF;

    --------------------------------------------------------------------
    -- Permission check
    --------------------------------------------------------------------
    PERFORM has_permission(v_staff_id, 'bookings.manage');
    IF NOT FOUND THEN
        RAISE EXCEPTION 'You do not have permission to check in vendors'
        USING errcode = 'P4002';
    END IF;

    --------------------------------------------------------------------
    -- Validate booking exists
    --------------------------------------------------------------------
    SELECT status, payment_status 
      INTO v_status, v_payment_status
    FROM bookings
    WHERE id = p_booking_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Booking not found'
        USING errcode = 'P4000';
    END IF;

    IF v_payment_status NOT IN ('success', 'authorized') THEN
        RAISE EXCEPTION 'Booking is not fully paid'
        USING errcode = 'P4000';
    END IF;

    --------------------------------------------------------------------
    -- Validate booking_date belongs to booking
    --------------------------------------------------------------------
    SELECT checked_in_at INTO v_checked_at
    FROM booking_dates
    WHERE id = p_booking_date_id
      AND booking_id = p_booking_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Invalid booking_date for this booking'
        USING errcode = 'P4000';
    END IF;

    --------------------------------------------------------------------
    -- Check if already checked in today
    --------------------------------------------------------------------
    IF v_checked_at IS NOT NULL THEN
        RAISE EXCEPTION 'Vendor already checked in for this day'
        USING errcode = 'P4001';
    END IF;

    --------------------------------------------------------------------
    -- Perform check-in
    --------------------------------------------------------------------
    UPDATE booking_dates
    SET 
        checked_in_at = now(),
        checked_in_by = v_staff_id
    WHERE id = p_booking_date_id;

    --------------------------------------------------------------------
    -- Success
    --------------------------------------------------------------------
    RETURN json_build_object(
        'status', 'success',
        'message', 'Vendor successfully checked in'
    );
END$function$
;

CREATE OR REPLACE FUNCTION public.create_credentials(p_source text, p_key text, p_value text, p_meta jsonb)
 RETURNS void
 LANGUAGE plpgsql
AS $function$begin
  -- Deactivate all existing keys
  update cred
   set is_active = false
   WHERE source = p_source
   AND key = p_key;

  -- Insert new key as active (or update if you prefer upsert on a unique constraint)
  insert into cred (key, value, source, meta, is_active)
  values (p_key, p_value, p_source,p_meta,  true);
end;$function$
;

CREATE OR REPLACE FUNCTION public.lookup_vendor_in_market(p_email text, p_market_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$DECLARE
  v_user_id uuid;
  v_profile jsonb;
  v_bookings jsonb;
BEGIN
  -------------------------------------------------------------------
  -- 1. Permission check
  -------------------------------------------------------------------
  IF NOT has_permission(auth.uid(), 'vendors.lookup') THEN
    RAISE EXCEPTION 
      'Permission denied (%). Required: neccesary permission', 
      auth.uid() USING ERRCODE = 'P4030';
  END IF;


  -------------------------------------------------------------------
  -- 2. Fetch user profile + latest KYC in ONE query
  -------------------------------------------------------------------
  SELECT 
    p.id,
    jsonb_build_object(
      'user_id', p.id,
      'email', p.email,
      'full_name', p.full_name,
      'phone_number', p.phone_number,
      'company_name', p.company_name,
      'kyc_status', k.status,
      'kyc_id', k.id
    )
  INTO v_user_id, v_profile
  FROM public.profiles p
  LEFT JOIN LATERAL (
    SELECT id, status
    FROM public.kyc_applications
    WHERE user_id = p.id
    ORDER BY created_at DESC
    LIMIT 1
  ) k ON TRUE
  WHERE LOWER(p.email) = LOWER(p_email)
  LIMIT 1;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No user found for email %', p_email USING ERRCODE = 'P4040';
  END IF;


  -------------------------------------------------------------------
  -- 3. Fetch all bookings for this market
  -------------------------------------------------------------------
  SELECT COALESCE(jsonb_agg(
           jsonb_build_object(
             'id', b.id,
             'market_id', b.market_id,
             'invoice_number', b.invoice_number,
             'selected_dates', b.selected_dates,
             'status', b.status,
             'payment_status', b.payment_status,
             'total_amount', b.total_amount,
             'paid_amount', b.paid_amount,
             'days_count', b.days_count,
             'created_at', b.created_at
           )
         ), '[]'::jsonb)
  INTO v_bookings
  FROM public.bookings b
  WHERE b.user_id = v_user_id
    AND b.market_id = p_market_id;



  -------------------------------------------------------------------
  -- 4. Return final JSON payload
  -------------------------------------------------------------------
  RETURN jsonb_build_object(
    'profile', v_profile,
    'bookings', v_bookings
  );

END$function$
;

CREATE OR REPLACE FUNCTION public.undo_checkin_vendor(p_booking_id uuid, p_booking_date_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$DECLARE
    v_staff_id uuid;
    v_exists boolean;
    v_status text;
    v_payment_status text;
    v_checked_at timestamptz;
BEGIN
    --------------------------------------------------------------------
    -- Authenticated staff ID
    --------------------------------------------------------------------
    v_staff_id := auth.uid();
    IF v_staff_id IS NULL THEN
        RAISE EXCEPTION 'Unauthenticated user'
        USING errcode = 'P4000';
    END IF;

    --------------------------------------------------------------------
    -- Permission check
    --------------------------------------------------------------------
    PERFORM has_permission(v_staff_id, 'bookings.undo.checkin');
    IF NOT FOUND THEN
        RAISE EXCEPTION 'You do not have permission to check in vendors'
        USING errcode = 'P4002';
    END IF;

    --------------------------------------------------------------------
    -- Validate booking_date belongs to booking
    --------------------------------------------------------------------
    SELECT checked_in_at INTO v_checked_at
    FROM booking_dates
    WHERE id = p_booking_date_id
      AND booking_id = p_booking_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Invalid booking_date for this booking'
        USING errcode = 'P4000';
    END IF;

    --------------------------------------------------------------------
    -- Check if already checked in today
    --------------------------------------------------------------------
    IF v_checked_at IS NULL THEN
        RAISE EXCEPTION 'Undo Vendor check in triggered already for this day'
        USING errcode = 'P4001';
    END IF;

    --------------------------------------------------------------------
    -- Perform check-in
    --------------------------------------------------------------------
    UPDATE booking_dates
    SET 
        checked_in_at = NULL,
        checked_in_by = NULL
    WHERE id = p_booking_date_id;

    --------------------------------------------------------------------
    -- Success
    --------------------------------------------------------------------
    RETURN json_build_object(
        'status', 'success',
        'message', 'Undo Vendor checked in successfully'
    );
END$function$
;

grant delete on table "public"."cred" to "anon";

grant insert on table "public"."cred" to "anon";

grant references on table "public"."cred" to "anon";

grant select on table "public"."cred" to "anon";

grant trigger on table "public"."cred" to "anon";

grant truncate on table "public"."cred" to "anon";

grant update on table "public"."cred" to "anon";

grant delete on table "public"."cred" to "authenticated";

grant insert on table "public"."cred" to "authenticated";

grant references on table "public"."cred" to "authenticated";

grant select on table "public"."cred" to "authenticated";

grant trigger on table "public"."cred" to "authenticated";

grant truncate on table "public"."cred" to "authenticated";

grant update on table "public"."cred" to "authenticated";

grant delete on table "public"."cred" to "service_role";

grant insert on table "public"."cred" to "service_role";

grant references on table "public"."cred" to "service_role";

grant select on table "public"."cred" to "service_role";

grant trigger on table "public"."cred" to "service_role";

grant truncate on table "public"."cred" to "service_role";

grant update on table "public"."cred" to "service_role";

grant delete on table "public"."payment_sync" to "anon";

grant insert on table "public"."payment_sync" to "anon";

grant references on table "public"."payment_sync" to "anon";

grant select on table "public"."payment_sync" to "anon";

grant trigger on table "public"."payment_sync" to "anon";

grant truncate on table "public"."payment_sync" to "anon";

grant update on table "public"."payment_sync" to "anon";

grant delete on table "public"."payment_sync" to "authenticated";

grant insert on table "public"."payment_sync" to "authenticated";

grant references on table "public"."payment_sync" to "authenticated";

grant select on table "public"."payment_sync" to "authenticated";

grant trigger on table "public"."payment_sync" to "authenticated";

grant truncate on table "public"."payment_sync" to "authenticated";

grant update on table "public"."payment_sync" to "authenticated";

grant delete on table "public"."payment_sync" to "service_role";

grant insert on table "public"."payment_sync" to "service_role";

grant references on table "public"."payment_sync" to "service_role";

grant select on table "public"."payment_sync" to "service_role";

grant trigger on table "public"."payment_sync" to "service_role";

grant truncate on table "public"."payment_sync" to "service_role";

grant update on table "public"."payment_sync" to "service_role";

create policy "Users with booking.manage can update"
on "public"."booking_dates"
as permissive
for update
to public
using ((EXISTS ( SELECT 1
   FROM bookings
  WHERE ((bookings.id = booking_dates.booking_id) AND has_any_permission(auth.uid(), ARRAY['bookings.manage'::text, 'bookings.undo.checkin'::text])))));


