-- Create settings table with same structure as cred table
CREATE TABLE IF NOT EXISTS "public"."settings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "key" text not null,
    "value" text not null,
    "source" text not null,
    "is_active" boolean not null,
    "meta" jsonb not null
);

-- Create primary key
CREATE UNIQUE INDEX settings_pkey ON public.settings USING btree (id);
ALTER TABLE "public"."settings" ADD CONSTRAINT "settings_pkey" PRIMARY KEY USING INDEX "settings_pkey";

-- Enable RLS
ALTER TABLE "public"."settings" ENABLE ROW LEVEL SECURITY;

-- Grant permissions to roles
-- Note: No grants to "anon" - settings should only be accessible to authenticated admins
-- RLS policies will enforce this via permission checks

GRANT DELETE ON TABLE "public"."settings" TO "authenticated";
GRANT INSERT ON TABLE "public"."settings" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."settings" TO "authenticated";
GRANT SELECT ON TABLE "public"."settings" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."settings" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."settings" TO "authenticated";
GRANT UPDATE ON TABLE "public"."settings" TO "authenticated";

GRANT DELETE ON TABLE "public"."settings" TO "service_role";
GRANT INSERT ON TABLE "public"."settings" TO "service_role";
GRANT REFERENCES ON TABLE "public"."settings" TO "service_role";
GRANT SELECT ON TABLE "public"."settings" TO "service_role";
GRANT TRIGGER ON TABLE "public"."settings" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."settings" TO "service_role";
GRANT UPDATE ON TABLE "public"."settings" TO "service_role";

-- Create permissions
INSERT INTO public.permissions (key, name, description, category)
VALUES 
  ('settings.view', 'View Settings', 'View platform settings', 'settings'),
  ('settings.manage', 'Manage Settings', 'Create, update, and delete platform settings', 'settings')
ON CONFLICT (key) DO NOTHING;

-- Assign permissions to admin role
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT 
  r.id as role_id,
  p.id as permission_id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE r.key = 'admin'
  AND p.key IN ('settings.view', 'settings.manage')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Create RLS policies
CREATE POLICY "Users with settings.view can view settings"
  ON public.settings FOR SELECT
  USING (has_permission(auth.uid(), 'settings.view'));

CREATE POLICY "Users with settings.manage can manage settings"
  ON public.settings FOR ALL
  USING (has_permission(auth.uid(), 'settings.manage'))
  WITH CHECK (has_permission(auth.uid(), 'settings.manage'));

-- Allow vendors to read platform settings (e.g. min_bookings for Pay Later eligibility)
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT r.id AS role_id, p.id AS permission_id
FROM public.roles r
JOIN public.permissions p ON p.key = 'settings.view'
WHERE r.key = 'vendor'
ON CONFLICT (role_id, permission_id) DO NOTHING;
